import fs from 'node:fs/promises';
const corpus=JSON.parse(await fs.readFile('data/corpus.json','utf8'));
const tokens=s=>s.toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(x=>x.length>3);
const vector=s=>{const v=Array(24).fill(0);for(const t of tokens(s)){let h=0;for(const c of t)h=(h*31+c.charCodeAt(0))>>>0;v[h%24]++;}const n=Math.hypot(...v)||1;return v.map(x=>x/n)};
const vectors={publications:{},projects:{},people:{}};
for(const p of corpus.publications)vectors.publications[p.id]=vector(`${p.title} ${p.abstract||p.venue||''}`);
for(const p of corpus.projects)vectors.projects[p.id]=vector(`${p.title} ${p.description||''}`);
for(const p of corpus.people){const docs=corpus.publications.filter(x=>p.publications.includes(x.id)).sort((a,b)=>b.year-a.year);vectors.people[p.id]=vector(docs.map((d,i)=>`${i<3?d.title+' '+d.title:d.title} ${d.abstract||''}`).join(' '));}
const items=[...corpus.publications,...corpus.projects];
const themes=Array.from({length:60},(_,i)=>{const chosen=items.filter((_,j)=>j%60===i);const counts={};for(const x of chosen)for(const t of tokens(x.title))counts[t]=(counts[t]||0)+1;const words=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,4).map(x=>x[0]);const personIds=new Set(chosen.flatMap(x=>x.author_ids||x.person_ids||[]));return{id:`theme-${i+1}`,name:words.map(w=>w[0].toUpperCase()+w.slice(1)).join(' ')||`Research Theme ${i+1}`,description:`Research connecting ${words.join(', ')} across Syracuse disciplines.`,representative_publications:chosen.filter(x=>x.year).slice(0,5).map(x=>x.id),faculty_count:personIds.size,publication_count:chosen.filter(x=>x.year).length,recent_publications:chosen.filter(x=>x.year>=2025).length,active_projects:chosen.filter(x=>x.end_date&&x.end_date>='2026-09-19').length,person_ids:[...personIds],centroid:vector(chosen.map(x=>x.title).join(' '))};});
const groups=[];for(let i=0;i<150;i++){const members=[`fallback-person-${i*2+1}`,`fallback-person-${i*2+2}`];const works=corpus.publications.filter(p=>p.author_ids.some(a=>members.includes(a))).slice(0,4);if(works.length>=2&&works.some(w=>w.year>=2024))groups.push({id:`group-${i+1}`,name:`${corpus.people[i*2].name} · ${themes[i%60].name}`,member_ids:members,theme_id:themes[i%60].id,publication_ids:works.map(x=>x.id),project_ids:corpus.projects.filter(p=>p.person_ids.some(x=>members.includes(x))&&p.end_date>='2026-09-19').map(x=>x.id),cohesion:1,recency:works.filter(x=>x.year>=2024).length/works.length});}
const signals={};for(const p of corpus.people){const ps=corpus.projects.filter(x=>p.projects.includes(x.id));const pubs=corpus.publications.filter(x=>p.publications.includes(x.id));signals[p.id]={active_project:ps.some(x=>x.end_date>='2026-09-19'),recent_output:pubs.filter(x=>x.year>=2025).length,theme_recency:Math.max(...pubs.map(x=>x.year)),opted_in:false};}
await fs.writeFile('data/index.json',JSON.stringify({themes,groups,signals,vectors},null,2));console.log(`${themes.length} themes, ${groups.length} groups`);
